# Generated by Django 3.0.6 on 2020-06-05 04:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'Name should be 5 chars long'), django.core.validators.MaxLengthValidator(50, 'Name shoild not be longer than 50 chars'), django.core.validators.EmailValidator('Invalid Email')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.BigIntegerField(default=0, unique=True, validators=[django.core.validators.MinValueValidator(6666666666, 'Invalid Phone Number'), django.core.validators.MaxValueValidator(9999999999, 'Invalid Phone Number')], verbose_name='Phone'),
        ),
    ]
