# Generated by Django 3.0.7 on 2020-11-27 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20200615_2013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
