# Generated by Django 3.0.7 on 2020-11-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_delete_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default=0, max_length=255, verbose_name='Address'),
        ),
    ]
